version: "3.8"

services:
  ml-backend:
    container_name: ml_yolov8
    image: label_studio_ml_yolov8
    build: .
    environment:
      - MODEL_DIR=/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
      - LABEL_STUDIO_HOST=http://172.16.54.101:8080
      - LABEL_STUDIO_ACCESS_TOKEN=3a73db2acb8a48286add1a2a9b316a6b7392ba7f
    ports:
      - "9090:9090"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
